### ISSUE TITLE
Create a homebrew-brew repository

### ISSUE THREAD

**Issue by pedromanoel** [markus-wa/cq#12]
Please create a repository such as this one https://github.com/pedromanoel/homebrew-brew so people can install your awesome tool using homebrew!

The install process becomes `brew install markus-wa/brew/cq`

**Comment by markus-wa** [comment]
Thanks for the suggestion @pedromanoel - I'll take a look at this 🙂

**Comment by markus-wa** [comment]
You should be able to install it via Homebrew now

    brew install markus-wa/brew/cq

readme update: 61930d59fb22bedaf6342762a697fe5921aa27ca
formula: https://github.com/markus-wa/homebrew-brew/blob/main/Formula/cq.rb
