### ISSUE TITLE
--color=auto should detect if output supports colors

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/cq#18]
see https://github.com/markus-wa/cq/issues/15#issuecomment-1294566333

> pretty was released with automatic logic for enabling colors. Seems pretty straightforward: https://github.com/AvisoNovate/pretty/commit/7cb0c16ec50bcbd9930ae9ec10a6aa7c1dc370a1

**Comment by Macroz** [comment]
So should we only check for existence of `System.console()` or the REPL trick too?

```clj
 (or (contains? (set (loaded-libs)) 'nrepl.core)
     (System/console))
```

I guess we don't need the env var check?

**Comment by markus-wa** [comment]
the above looks good. REPL trick is probably a good idea but env var not needed IMO (it's not a standard env var)

**Comment by Macroz** [comment]
Yeah, that's what I thought. I'll make a PR sometime :+1:

**Comment by Macroz** [comment]
Here's the PR https://github.com/markus-wa/cq/pull/20

**Comment by markus-wa** [comment]
amazing, thanks - will make a new release shortly :slightly_smiling_face:
