### ISSUE TITLE
Expose clojure.data.* inside SCI

### ISSUE THREAD

**Issue by farcaller** [markus-wa/cq#24]
It'd be useful to be able to parse JSON and the like for those insane payloads where people have JSON in JSON.

**Comment by markus-wa** [comment]
sounds good - definitely happy to take PRs for this :slightly_smiling_face:

**Comment by markus-wa** [comment]
I guess in the meantime the workaround is `cat some.json | cq ... | cq ...`

**Comment by markus-wa** [comment]
released here https://github.com/markus-wa/cq/releases/tag/2024.06.24-12.10
