### ISSUE TITLE
Add colored output for edn

### ISSUE THREAD

**Issue by se-neaxplore** [markus-wa/cq#9]
Would you be open to include [https://github.com/greglook/puget](https://github.com/greglook/puget) for colored edn output?

I patched it into my local copy and  the output looks like this:

![image](https://user-images.githubusercontent.com/65458631/132481814-e4f3c263-0caa-4491-9c03-2de9d02cfbe1.png)

**Comment by markus-wa** [comment]
Hi @se-neaxplore 

I would be more than happy to accept a PR for this - I've thought about adding this as well but never got around to it myself! :smile:

**Comment by se-neaxplore** [comment]
Awesome :)

**Comment by markus-wa** [comment]
New release here: https://github.com/markus-wa/cq/releases/tag/v0.1.3, binaries will be up soon (though it sounds like you've already built it locally :smile:)

Thanks again!

**Comment by se-neaxplore** [comment]
Yeah built them on my machine. Only possible because of those  simple package scripts, really nice  :+1:
